In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("../data/Dataset.csv")
df.sample(3)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
6888,3191-CSNMG,Female,0,Yes,Yes,3,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,80.70,239.45,No
5274,6723-WSNTY,Female,1,Yes,No,66,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,One year,Yes,Credit card (automatic),108.10,7181.95,No
2025,1488-PBLJN,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),116.85,8477.7,No

In [16]:
new_df = df.copy()
print(new_df.sample(3))
df.columns

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
4795  6532-YLWSI  Female              0     Yes         No      53
6397  7994-XIRTR    Male              1      No         No      54
5022  2599-CIPQE    Male              0     Yes        Yes      71

     PhoneService MultipleLines InternetService       OnlineSecurity  ...  \
4795          Yes            No              No  No internet service  ...
6397          Yes            No             DSL                   No  ...
5022          Yes            No     Fiber optic                  Yes  ...

         DeviceProtection          TechSupport          StreamingTV  \
4795  No internet service  No internet service  No internet service
6397                  Yes                  Yes                   No
5022                  Yes                  Yes                  Yes

          StreamingMovies  Contract PaperlessBilling  \
4795  No internet service  One year               No
6397                  Yes  One year               No
5022                  Yes  Two year               No

                  PaymentMethod MonthlyCharges  TotalCharges Churn
4795  Bank transfer (automatic)          20.80        1021.8   Yes
6397  Bank transfer (automatic)          65.25       3529.95    No
5022    Credit card (automatic)         109.30       7782.85    No

[3 rows x 21 columns]

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [11]:
new_df = new_df.drop(["customerID","gender"],axis=1)

In [12]:
def familysize(row):
    if row["Partner"] == "Yes" and row["Dependents"] == "No":
        return "has spouse"
    elif row["Partner"] == "No" and row["Dependents"] == "No":
        return "Alone"
    else:
        return "Has family"
new_df["familytype"] = new_df.apply(familysize,axis=1)
df["familytype"] = df.apply(familysize,axis=1)

In [13]:
new_df = new_df.drop(["Partner","Dependents"],axis=1)

In [14]:
new_df["SecurityScore"] = (
    (new_df["OnlineSecurity"] == "Yes").astype(int)
    + (new_df["OnlineBackup"] == "Yes").astype(int)
    + (new_df["DeviceProtection"] == "Yes").astype(int)
    + (new_df["TechSupport"] == "Yes").astype(int)
)
df["SecurityScore"] = (
    (df["OnlineSecurity"] == "Yes").astype(int)
    +(df["OnlineBackup"] == "Yes").astype(int)
    +(df["DeviceProtection"] == "Yes").astype(int)
    +(df["TechSupport"] == "Yes").astype(int)
)
new_df = new_df.drop(["OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport"],axis=1)

In [15]:
new_df = new_df.drop(["PaperlessBilling"],axis=1)
print(new_df.sample(1))

      SeniorCitizen  tenure PhoneService MultipleLines InternetService  \
3696              0       6          Yes            No             DSL

     StreamingTV StreamingMovies        Contract     PaymentMethod  \
3696          No              No  Month-to-month  Electronic check

      MonthlyCharges TotalCharges Churn  familytype  SecurityScore
3696           49.15        270.8   Yes  has spouse              1

In [16]:
new_df.sample(5)

,SeniorCitizen,tenure,PhoneService,MultipleLines,InternetService,StreamingTV,StreamingMovies,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Churn,familytype,SecurityScore
5546,0,4,No,No phone service,DSL,No,No,Month-to-month,Mailed check,42.40,146.4,No,Alone,3
5038,0,10,Yes,No,No,No internet service,No internet service,One year,Mailed check,19.30,185.2,No,Alone,0
4402,0,39,No,No phone service,DSL,Yes,No,Month-to-month,Credit card (automatic),48.95,1880.85,Yes,Alone,3
3801,1,18,Yes,Yes,Fiber optic,No,No,Month-to-month,Electronic check,85.45,1505.85,Yes,Alone,2
3454,1,29,No,No phone service,DSL,No,No,Month-to-month,Mailed check,35.65,1025.15,No,Has family,2

In [17]:
new_df["EntertainmentScore"] = (
    (new_df["StreamingTV"] == "Yes").astype(int)
    +(new_df["StreamingMovies"] == "Yes").astype(int)
)
df["EntertainmentScore"] = (
    (df["StreamingTV"] == "Yes").astype(int)
    +(df["StreamingMovies"] == "Yes").astype(int)
)
new_df = new_df.drop(["StreamingTV","StreamingMovies"],axis=1)

In [18]:
new_df.sample(3)

,SeniorCitizen,tenure,PhoneService,MultipleLines,InternetService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Churn,familytype,SecurityScore,EntertainmentScore
834,1,4,Yes,No,Fiber optic,Month-to-month,Electronic check,78.85,292.8,Yes,Alone,0,1
4485,0,66,Yes,Yes,DSL,Two year,Bank transfer (automatic),91.70,6075.9,No,has spouse,4,2
375,0,43,Yes,Yes,DSL,One year,Credit card (automatic),85.10,3662.25,No,Alone,3,2

In [19]:
df.sample(3)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,familytype,SecurityScore,EntertainmentScore
1337,6265-FRMTQ,Male,0,No,No,31,Yes,No,No,No internet service,...,No internet service,Two year,No,Bank transfer (automatic),20.40,609.1,No,Alone,0,0
6688,0064-SUDOG,Female,0,Yes,Yes,12,Yes,No,No,No internet service,...,No internet service,Two year,No,Bank transfer (automatic),20.30,224.5,No,Has family,0,0
5047,8149-AIQCG,Male,0,No,No,39,Yes,Yes,Fiber optic,No,...,No,Month-to-month,Yes,Credit card (automatic),73.15,2730.85,No,Alone,0,0

In [20]:
def duration(row):
    if row["tenure"] > 25:
        return "Old"
    elif row["tenure"] < 10:
        return "New"
    else:
        return "Moderate"
new_df["Customertype"] = new_df.apply(duration,axis=1)
df["Customertype"] = df.apply(duration,axis=1)
new_df = new_df.drop(["tenure"],axis=1)

In [21]:
new_df.sample(3)

,SeniorCitizen,PhoneService,MultipleLines,InternetService,Contract,PaymentMethod,MonthlyCharges,TotalCharges,Churn,familytype,SecurityScore,EntertainmentScore,Customertype
2666,0,Yes,No,DSL,Two year,Credit card (automatic),79.50,5196.1,No,Has family,3,2,Old
6427,0,Yes,No,No,Two year,Mailed check,20.15,802.35,No,Alone,0,0,Old
6897,0,Yes,No,DSL,Month-to-month,Bank transfer (automatic),80.40,4981.15,No,Alone,3,2,Old

In [22]:
df.sample(3)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,familytype,SecurityScore,EntertainmentScore,Customertype
3411,7056-IMHCC,Male,1,Yes,No,53,Yes,Yes,Fiber optic,No,...,Month-to-month,Yes,Electronic check,101.90,5549.4,Yes,has spouse,1,2,Old
6094,7493-GVFIO,Male,0,No,No,57,Yes,No,No,No internet service,...,Two year,No,Credit card (automatic),20.55,1252.85,No,Alone,0,0,Old
3036,4702-HDRKD,Male,0,No,No,67,No,No phone service,DSL,Yes,...,One year,Yes,Bank transfer (automatic),49.35,3321.35,No,Alone,3,1,Old

In [23]:
def risk(row):
    if (row["Contract"] == "Month-to-month" and row["PaymentMethod"] == "Electronic check") and (row["InternetService"] == "Fiber optic" and row["TechSupport"] == "No"):
        return "High risk"
    elif (row["Contract"] == "Month-to-month" and row["PaymentMethod"] == "Mailed check") and (row["InternetService"] == "DSL" and row["SeniorCitizen"] == 0):
        return "Medium risk"
    else:
        return "Low risk"
df["RiskType"] = df.apply(risk,axis=1)

In [24]:
print(df.sample(3))
df.columns

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
5218  2923-ARZLG    Male              0     Yes        Yes       0
140   3146-MSEGF  Female              1     Yes        Yes      72
6719  2509-TFPJU    Male              0     Yes         No      72

     PhoneService MultipleLines InternetService       OnlineSecurity  ...  \
5218          Yes            No              No  No internet service  ...
140           Yes           Yes             DSL                  Yes  ...
6719          Yes           Yes              No  No internet service  ...

     PaperlessBilling            PaymentMethod MonthlyCharges TotalCharges  \
5218              Yes             Mailed check          19.70
140               Yes  Credit card (automatic)          88.05      6425.65
6719               No  Credit card (automatic)          25.75       1864.2

     Churn  familytype SecurityScore EntertainmentScore  Customertype  \
5218    No  Has family             0                  0           New
140     No  Has family             4                  2           Old
6719    No  has spouse             0                  0           Old

      RiskType
5218  Low risk
140   Low risk
6719  Low risk

[3 rows x 26 columns]

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'familytype', 'SecurityScore', 'EntertainmentScore', 'Customertype',
       'RiskType'],
      dtype='str')

In [25]:
df = df.drop(["StreamingTV","StreamingMovies","gender","MultipleLines"],axis=1)

In [26]:
print(df.sample(3))
df.columns

      customerID  SeniorCitizen Partner Dependents  tenure PhoneService  \
4863  8727-JQFHV              0     Yes        Yes      57          Yes
6735  6365-HITVU              0     Yes        Yes      71          Yes
2458  7516-GMHUV              1     Yes         No      50          Yes

     InternetService       OnlineSecurity         OnlineBackup  \
4863              No  No internet service  No internet service
6735             DSL                  Yes                  Yes
2458     Fiber optic                  Yes                   No

         DeviceProtection  ... PaperlessBilling            PaymentMethod  \
4863  No internet service  ...               No             Mailed check
6735                  Yes  ...               No  Credit card (automatic)
2458                  Yes  ...              Yes  Credit card (automatic)

     MonthlyCharges TotalCharges  Churn  familytype SecurityScore  \
4863          20.75      1123.15     No  Has family             0
6735          87.25       6328.7     No  Has family             4
2458         105.05       5163.3     No  has spouse             2

     EntertainmentScore  Customertype  RiskType
4863                  0           Old  Low risk
6735                  2           Old  Low risk
2458                  2           Old  Low risk

[3 rows x 22 columns]

Index(['customerID', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'familytype', 'SecurityScore', 'EntertainmentScore', 'Customertype',
       'RiskType'],
      dtype='str')

In [29]:
df["Churn_binary"] = df["Churn"].map({
    "Yes": 1,
    "No": 0
})
risk_churn = (
    df.groupby("RiskType")["Churn_binary"]
      .mean()
      .mul(100)
      .round(2)
)
print(risk_churn)
df["RiskType"].value_counts()
df.groupby("RiskType")["Churn_binary"].agg(
    ["count", "mean"]
)
df.groupby("RiskType")["Churn_binary"].agg(
    ["count", "mean"]
)

RiskType
High risk      62.92
Low risk       18.93
Medium risk    29.33
Name: Churn_binary, dtype: float64

             count      mean
RiskType
High risk     1138  0.629174
Low risk      5564  0.189252
Medium risk    341  0.293255

In [50]:
df.to_csv("processed.csv",index=False)
new_df.to_csv("Optimized.csv",index=False)